---
appname: Mnemosyne
app:
  # For local-scan.js
  home_host: pike.dyn.hexten.net
  table_suffix: aryo_activity_log
  # Event padding in minutes
  padding:
    before: 10
    after: 5
db:
  database: mnemosyne
  username: root
  password: null
  dialect: mysql
