---
appname: Mnemosyne
app:
  # For local-scan.js
  home_host: pike.dyn.hexten.net
  table_suffix: aryo_activity_log
  # Event padding in minutes
  padding:
    before: 10
    after: 5
db:
  database: mnemosyne
  username: root
  password: null
  dialect: mysql
couch:
  url: "http://localhost:5984/mnemosyne"
  options:
    auth:
      username: mnemosyne
      password: "f7a49ad9-a6a8-40d2-9447-8c9697a37312"
